SET ANSI_NULLS ON;
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;

IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'LocalCirculation')
BEGIN
    CREATE DATABASE LocalCirculation;
END
GO

USE LocalCirculation;
GO

IF DATABASE_PRINCIPAL_ID('Bff_Role') IS NULL
BEGIN
    CREATE ROLE [Bff_Role] AUTHORIZATION dbo;
END

IF DATABASE_PRINCIPAL_ID('Service_Role') IS NULL
BEGIN
    CREATE ROLE [Service_Role] AUTHORIZATION dbo;
END
